name: "Build & Cache"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
      - run: nix --impure flake check
        env:
          NIXPKGS_ALLOW_BROKEN: 1
      - run: nix build .#memflow .#cloudflow
